import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Layout from "../components/layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Layout>
    <h1>header</h1>

    <h1>content container</h1>

    </Layout>

    </div>
  )
}
