import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>This is a portfolio website in the making</h1>

    <h3>Come back latter to enjoy the full experience</h3>


    </div>
  )
}
